export const PERIODS = {
  past24h: 1,
  past7d: 7,
  past30d: 30,
  allTime: 0,
  range: -1,
}

export const ANALYTICS_TYPE = {
  DELETED_ACCOUNT: 'DELETED_ACCOUNT',
  INVITE_MYINS_USER: 'INVITE_MYINS_USER',
  INVITE_NON_USER: 'INVITE_NON_USER',
  ACCEPTED_MYINS_USER: 'ACCEPTED_MYINS_USER',
  ACCEPTED_NON_USER: 'ACCEPTED_NON_USER'
}
